### ISSUE TITLE
Decide on versioning scheme

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort-governance#18]
Decide on the versioning scheme to use for ORT releases 

Options:
- https://calver.org/ -> YY.MM.MINOR.MICRO (Teradata version)
- https://semver.org/

**Comment by tsteenbe** [comment]
Whatever we pick we should test first whether it works with packing tools - Philippe switched ScanCode to Calver and he wanted YY.minor.micro but had to settle for YY.M.D due to what the Python packaging tools accept as a version number.

**Comment by sschuberth** [comment]
We've implemented SemVer by now, see https://github.com/oss-review-toolkit/ort/pull/7455.
