### ISSUE TITLE
Obtain approval from LF for ORT Charter update

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort-governance#2]
In the meeting of April 30 the TSC agreed to update ORT's charter to https://github.com/oss-review-toolkit/ort-governance/commit/3e12ed16e8d2d761705d5e08605ead0eafb4fc79

This issue was created to help track the status of LF's approval

**Comment by sschuberth** [comment]
@tsteenbe is waiting for a meeting with Mike Dolan (general manager and lawyer from LF) to clarify details.

**Comment by tsteenbe** [comment]
Charter change is with LF legal queue for review.

**Comment by kestewart** [comment]
Charter change has been approved by LF legal today.    Update can be applied.
