### ISSUE TITLE
ORT domains do not properly support HTTPS

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort-governance#24]
https://ossreviewtoolkit.org does not work at all and https://oss-review-toolkit.org causes SSL_ERROR_BAD_CERT_DOMAIN because the certificate does not match the domain. If we want to use these domains to link to ORT HTTPS should work without any browser warnings.

**Comment by sschuberth** [comment]
This used to work. Might be a side-effect of renaming `master` to `main` in https://github.com/oss-review-toolkit/oss-review-toolkit.github.io. I'll try something...

**Comment by sschuberth** [comment]
Should be fixed now by a (more or less) "dummy" commit at https://github.com/oss-review-toolkit/oss-review-toolkit.github.io/commit/91a804c7c316c134e62ec186efb89cb575204def.
