### ISSUE TITLE
Link to contributing.md in ort-governance repository.

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort-governance#5]
The reference contributing.md is located in the ort-governance repository:
https://github.com/oss-review-toolkit/ort-governance/blob/master/CONTRIBUTING.md

All other repositories in this organization should link to it. There probably is a GitHub feature to automate this.

**Comment by tsteenbe** [comment]
Fixed in https://github.com/oss-review-toolkit/ort/commit/d52efca76e58b858b45e5531eeeb83f0c650edc4
