### ISSUE TITLE
Replace the copyright statements in the license headers of ORT with a generic statement

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort-governance#6]
Replace the explicit mentioning of copyright holders in the license headers of ORT with the generic statement "Copyright 201x-2020 The OSS Review Toolkit contributors". Check with LF if there are legal issues with that and if we need approval from every single copyright holder.

**Comment by sschuberth** [comment]
@tsteenbe is waiting for a meeting with Mike Dolan (general manager and lawyer from LF) to clarify details.

**Comment by tsteenbe** [comment]
Guidance provided by LF:  "If all the contributors agree, you can start using "Copyright the OSS Review Toolkit contributors", as long as the contributors are listed in a file in the project."

Propose we do the following:
- Draft a proposal to request the main copyright holder e.g. ORT TSC would like to simplify copyright holder statement in all its source code files. Our proposal is update the copyright for each file to "Copyright 201x-202x The OSS Review Toolkit contributors" and move you copyright to a file name X in the root of the code repository...
-  All ORT TSC members to vote on the text
- @tsteenbe  and @tsteenbe  propose the change to their respective companies
- Update [CONTRIBUTING.md](https://github.com/oss-review-toolkit/ort/blob/master/CONTRIBUTING.md) to mention the copyright holder that should but used. Possibly add a CI check.

@sschuberth  @mnonnenmacher  @fviernau To you agree to the above? Or have an alternative proposal?

**Comment by tsteenbe** [comment]
Maybe we should look into adopting [AUTHORS Certificate](https://github.com/berneout/authors-certificate) e.g. Authors file in the root of the repo. Found it via https://writing.kemitchell.com/2016/05/13/License-from-Who.html

**Comment by sschuberth** [comment]
Doesn't our [DCO check](https://probot.github.io/apps/dco/) already cover the intent of the AUTHORS Certificate? At least the wordings of the first paragraphs sound very similar. IMO we just need to make it easier to discover who the actual authors / contributors are. Besides [GitHub showing this](https://github.com/oss-review-toolkit/ort/graphs/contributors), we could leverage something like the [all-contributors GitHub action](https://github.com/all-contributors/app).

**Comment by sschuberth** [comment]
> Besides [GitHub showing this](https://github.com/oss-review-toolkit/ort/graphs/contributors), we could leverage something like the [all-contributors GitHub action](https://github.com/all-contributors/app).

More action for potential use:

- https://github.com/wow-actions/update-authors (`AUTHORS` file)
- https://github.com/minicli/action-contributors (`CONTRIBUTORS` file)
- https://github.com/BobAnkh/add-contributors ("Contributors" section)
- https://github.com/test-room-7/action-update-file (generic updating of files)

**Comment by tsteenbe** [comment]
I like how PURL project did its copyrights see https://github.com/package-url/purl-spec/blob/master/mit.LICENSE#L1 but would make some change. I propose 'Copyright (c) the ORT authors' to each code file and then add a NOTICE with copyright attribution to the root of the code repository so we align with ORT's [Apache-2.0 license lines 106-121](https://github.com/oss-review-toolkit/ort/blob/main/LICENSE#L106-L121). 

Open discussions points for me:
1) What should be the contents of NOTICE file?
Propose to use  authors in the various copyright statements e.g. HERE Europe B.V, Bosch.io etc. so it a straightforward migration and then in a second step look how to automate generation of the NOTICE file.
2) How do we organize each authors to give its permission for this changes in writting?

**Comment by tsteenbe** [comment]
Following the https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code#what-if-there-are-many-authors-or-copyright-is-held-by-a-legal-entity I propose the following change to ORT code base

1. Move all existing copyright statements found https://github.com/oss-review-toolkit/ort into a new NOTICE file in the root of https://github.com/oss-review-toolkit/ort
2.   The `NOTICE` file will look something like the below. Note we should de-duplicate years similar to ORT's own logic.

```
The ORT Project

Copyright (C) 2017-2022 HERE Europe B.V.
Copyright (C) 2019-2020 Bosch Software Innovations GmbH
Copyright (C) 2020-2022 Bosch.IO GmbH
...
```
3.  Add new copyright statement to each code file `Copyright (c) YearA - YearB The ORT Project Authors (See NOTICE file in project root)`. Alternatively, we could also do `Copyright (c) YearA - YearB The ORT Project Authors <https://github.com/oss-review-toolkit/ort/tree/NOTICE>` but the link would in this case always point to the NOTICE of the latest dev version of ORT which may not be desirable.
5.  Update the CONTRIBUTING.md to tell contributor to always add "Copyright (c) YearA - YearB The ORT Project Authors ..." and guidance on when their contribution is significant enough thtat the need to update the NOTICE.
6. Add a GitHub action to check each source code file in a pull request has the correct `Copyright (c) YearA - YearB The ORT Project Authors ...`

Note in the above proposal we do not ask contributors to sign over the copyright to a single entity therefore I do not see the need to ask each contributor to give his/her permission only the ORT TSC has to agree on this change.

**Comment by sschuberth** [comment]
Point 5. should already be covered by `detekt` checks that run in CI. However, we probably could auto-update the `NOTICE` file via a GitHub action (see [above](https://github.com/oss-review-toolkit/ort-governance/issues/6#issuecomment-1053443889)).

**Comment by tsteenbe** [comment]
@sschuberth  As per Matija not every contributor is an author so we have to be careful on auto-updating the `NOTICE` file.

**Comment by tsteenbe** [comment]
Discussed in TSC meeting of June 20, 2022. TSC is OK to go ahead with change @MarcelBochtler to run ORT over ORT to create the initial NOTICE file.

**Comment by tsteenbe** [comment]
In the TSC meeting of July 4th, 2022 ORT TSC decided to use `Copyright (C) YearA The ORT Project Authors (See NOTICE file in project root)`
